sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 129.204.43.32
before_install:
- openssl aes-256-cbc -K $encrypted_ea15fcd73a7f_key -iv $encrypted_ea15fcd73a7f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
script:
- npm install --registry=https://registry.npm.taobao.org
- npm run test
install:
- ssh -p22 ubuntu@129.204.43.32
      "
      cd ~/information_system/Information-system-backend/;
      npm run stop;
      git pull;
      cnpm install;
      npm run start;
      exit;"

